# Generated by Django 2.2.2 on 2019-06-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('published_year', models.IntegerField()),
                ('no_of_pages', models.IntegerField()),
                ('isbn', models.CharField(max_length=13)),
                ('cover', models.ImageField(upload_to='images/')),
                ('pdf', models.FileField(upload_to='files/')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
